apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: echo-replicas
          image: registry.cluster.wik.cloud/public/echo
